# 可以添加任意数量的启用世界
启用的世界:
  - "world"
  - "world_the_end"
  - "world_plot"

# 0~8 数字越大成熟度越高
偷菜后的作物成熟度: 0

# 偷菜后掉落农作物的概率, 1 为 100% 掉落, 0.5 为 50%
掉落概率: 0.5

# 设为 "" 可以隐藏提示消息
消息提示:
  偷菜成功: "偷菜成功"
  偷菜失败: "偷菜失败"

# 设为 true 采用左键偷菜模式, 有权限的就正常收菜, 没权限的就偷菜
# 设为 false 采用右键偷菜模式, 右键就是偷菜, 左键正常收菜
左键偷菜模式: true